import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "swiper/css";
import "swiper/css/pagination";
import "./globals.css";
import { Toaster } from "../components/ui/sonner";
import Navbar from "../components/Layout/Navbar";
import Providers from "../Providers";
import { getServerSession } from "next-auth";
import { authOptions } from "@/auth";
import Footer from "@/components/Layout/Footer";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Exclusive App",
  description: "Generated by exclusive",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-background text-foreground app`}
      >
        <Providers session={session}>
          <Navbar />
          <main className="content">{children}</main>
          <Toaster />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
