import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "swiper/css";
import "swiper/css/pagination";
import "./globals.css";
import { Toaster } from "@/Components/ui/sonner";
import Navbar from "@/Components/Layout/Navbar";
import Providers from "@/Providers";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-background text-foreground`}>
        <Providers>
          <Navbar />
          <main>{children}</main>
          <Toaster />
          {/* <Footer/> */}
        </Providers>
      </body>
    </html>
  );
}
